CREATE TABLE IF NOT EXISTS AADHAR_DATA (
    ID_NUMBER VARCHAR(20) PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    ADDRESS VARCHAR(255),
    DOB VARCHAR(20),
    GENDER VARCHAR(10),
    PHONE_NUMBER VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS PASSPORT_DATA (
    ID_NUMBER VARCHAR(20) PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    ADDRESS VARCHAR(255),
    DOB VARCHAR(20),
    GENDER VARCHAR(10),
    PHONE_NUMBER VARCHAR(15),
    EMAIL VARCHAR(50)
);
